defmodule SupportDeck.Repo.Migrations.CreateResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:webhook_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false
      add :external_id, :text, null: false
      add :event_type, :text, null: false
      add :payload, :map, null: false
      add :processed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:webhook_events, [:source, :external_id], unique: true)

    create unique_index(:webhook_events, [:source, :external_id],
             name: "webhook_events_unique_source_event_index"
           )

    create table(:tickets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :external_id, :text, null: false
      add :source, :text, null: false
      add :subject, :text, null: false
      add :body, :text
      add :severity, :text, null: false, default: "low"
      add :product_area, :text
      add :subscription_tier, :text, default: "free"
      add :customer_email, :text
      add :customer_id, :text
      add :assignee, :text
      add :front_conversation_id, :text
      add :slack_thread_ts, :text
      add :slack_channel_id, :text
      add :linear_issue_id, :text
      add :sla_deadline, :utc_datetime
      add :escalation_level, :bigint, default: 0
      add :ai_classification, :map
      add :ai_draft_response, :text
      add :ai_confidence, :float
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "new"
    end

    create index(:tickets, [:product_area])

    create index(:tickets, [:assignee])

    create index(:tickets, [:sla_deadline],
             where: "state NOT IN ('resolved', 'closed') AND sla_deadline IS NOT NULL"
           )

    create index(:tickets, [:state], where: "state NOT IN ('resolved', 'closed')")

    create index(:tickets, [:source, :external_id], unique: true)

    create unique_index(:tickets, [:source, :external_id],
             name: "tickets_unique_source_external_index"
           )

    create table(:ticket_activities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text, null: false
      add :actor, :text, null: false
      add :from_value, :text
      add :to_value, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :ticket_id,
          references(:tickets,
            column: :id,
            name: "ticket_activities_ticket_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:sla_policies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :subscription_tier, :text, null: false
      add :severity, :text, null: false
      add :first_response_minutes, :bigint, null: false
      add :resolution_minutes, :bigint
      add :escalation_thresholds, :map, null: false
      add :enabled, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:sla_policies, [:subscription_tier, :severity], unique: true)

    create unique_index(:sla_policies, [:subscription_tier, :severity],
             name: "sla_policies_unique_tier_severity_index"
           )

    create table(:rules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :trigger, :text, null: false
      add :conditions, :map, null: false
      add :actions_list, {:array, :map}, null: false, default: []
      add :enabled, :boolean, default: true
      add :priority, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:knowledge_docs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false
      add :content_type, :text, null: false
      add :source_url, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :integration, :text, null: false
      add :key_name, :text, null: false
      add :encrypted_value, :text, null: false
      add :value_hint, :text
      add :last_test_status, :text, default: "untested"
      add :last_test_message, :text
      add :last_tested_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:credentials, [:integration, :key_name],
             name: "credentials_unique_integration_key_index"
           )

    create table(:ai_triage_results, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :predicted_category, :text
      add :predicted_severity, :text
      add :confidence, :float
      add :is_repetitive, :boolean, default: false
      add :draft_response, :text
      add :human_accepted, :boolean
      add :human_override_category, :text
      add :response_used, :boolean
      add :processing_time_ms, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :ticket_id,
          references(:tickets,
            column: :id,
            name: "ai_triage_results_ticket_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:ai_triage_results, "ai_triage_results_ticket_id_fkey")

    drop table(:ai_triage_results)

    drop_if_exists unique_index(:credentials, [:integration, :key_name],
                     name: "credentials_unique_integration_key_index"
                   )

    drop table(:credentials)

    drop table(:knowledge_docs)

    drop table(:rules)

    drop_if_exists unique_index(:sla_policies, [:subscription_tier, :severity],
                     name: "sla_policies_unique_tier_severity_index"
                   )

    drop_if_exists index(:sla_policies, [:subscription_tier, :severity])

    drop table(:sla_policies)

    drop constraint(:ticket_activities, "ticket_activities_ticket_id_fkey")

    drop table(:ticket_activities)

    drop_if_exists unique_index(:tickets, [:source, :external_id],
                     name: "tickets_unique_source_external_index"
                   )

    drop_if_exists index(:tickets, [:source, :external_id])

    drop_if_exists index(:tickets, [:state])

    drop_if_exists index(:tickets, [:sla_deadline])

    drop_if_exists index(:tickets, [:assignee])

    drop_if_exists index(:tickets, [:product_area])

    drop table(:tickets)

    drop_if_exists unique_index(:webhook_events, [:source, :external_id],
                     name: "webhook_events_unique_source_event_index"
                   )

    drop_if_exists index(:webhook_events, [:source, :external_id])

    drop table(:webhook_events)
  end
end
